function nii_to_workbench(path_to_nii)

disp(['Converting' path_to_nii ' to ' path_to_nii '_R.shape.gii']);

system(['/Applications/workbench/bin_macosx64/wb_command '...
    '-volume-to-surface-mapping ''' path_to_nii ...
    ''' /Applications/workbench/Conte69_atlas-v2.LR.32k_fs_LR.wb/'...
    'Conte69.R.midthickness.32k_fs_LR.surf.gii ''' path_to_nii...
    '_R.shape.gii'' -trilinear'])

disp(['Converting' path_to_nii ' to ' path_to_nii '_L.shape.gii']);

system(['/Applications/workbench/bin_macosx64/wb_command '...
    '-volume-to-surface-mapping ''' path_to_nii ...
    ''' /Applications/workbench/Conte69_atlas-v2.LR.32k_fs_LR.wb/'...
    'Conte69.L.midthickness.32k_fs_LR.surf.gii ''' path_to_nii...
    '_L.shape.gii'' -trilinear'])
end




